services:
  nginx:
    image: nginx:1.21.3
    depends_on:
      - api
      - front
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
  api:
    build: ./api
    ports:
      - 4000:4000
    command: npm run dev
    volumes:
      - ./api/src/:/app/src/
  front:
    build: ./front
    command: sh -c "npm run build"
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - web-client-build:/app/build/
  db:
    image: mysql:5.7-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      # MYSQL_USER: user
      # MYSQL_PASSWORD: user
    ports:
      - "8006:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
volumes:
  web-client-build:
  mysql:
