services:
  api:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./server
    ports:
      - 4000:4000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  front:
    build: ./front
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./front/src/:/app/src/
  db:
    image: mysql:5.7-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      # MYSQL_USER: user
      # MYSQL_PASSWORD: user
    ports:
      - "8006:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
volumes:
  mysql:
