services:
  front:
    # build: ./front
    image: florianbeme/wns-client:latest
    command: sh -c "npm run build"
    environment:
      - NODE_ENV=staging
    ports:
      - 3000:3000
    volumes:
      - web-client-build:/app/build/
  db:
    image: mysql:5.7-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      # MYSQL_USER: user
      # MYSQL_PASSWORD: user
    ports:
      - "8006:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
  server:
    # build: ./server
    image: florianbeme/wns-server:latest
    expose:
      - 5000
    command: npm run deploy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL_DOCKER=mysql://root:root@db:3306/mydb?serverVersion=5.7
    # volumes:
    #   - ./server/src/:/app/src/
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - front
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
  mysql:
